version: '3.7'

services:
  web:
    image: nginx:latest
    volumes:      
      - ./php/:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
    depends_on:
      - php
    ports:
      - "8090:80"

  php:
    build:
      context: ./
      dockerfile: php_pdo.Dockerfile
    volumes:
      - ./php/:/var/www/html/

  bdd:
    image: mariadb:latest
    volumes:
      - ./bdd/docker/mariadb:/docker-entrypoint-initdb.d/
      - ./bdd/var/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'virtu'
    ports:
      - '3306:3306'
    command:
      'mysqld --innodb-flush-method=fsync'